name: Deploy GitHub pages

on:
  push:
    branches:
      - master

env:
  GH_PAGES_DIR: gh-pages-dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run build -- --env.out=$GH_PAGES_DIR
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: ${{ env.GH_PAGES_DIR }} # The folder the action should deploy.
          CLEAN: true
